export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const SET_FILTER_BY_PLATFORM = 'SET_FILTER_BY_PLATFORM';
export const SET_FILTER_BY_RATING = 'SET_FILTER_BY_RATING';
export const SAVE_WORKBOARD_ID = 'SAVE_WORKBOARD_ID';
